os: linux

dist: xenial

sudo: required

git:
  depth: 3

addons:
  apt:
    update:
    - true

before_install:
  #- git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 ~/toolchain/
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 ~/toolchain/
  - sudo chmod -R a+x ~/toolchain/*

install: true

script:
  #- export CROSS_COMPILE=~/toolchain/bin/arm-linux-androideabi-
  - export CROSS_COMPILE=~/toolchain/bin/arm-eabi-
  - export ARCH=arm
  - export KBUILD_BUILD_USER="ALGPHELLO"
  - export KBUILD_BUILD_HOST="fujitsu"
  - export ARCH_MTK_PLATFORM=mt6735
  #- make mt6737t-grandpplte_defconfig
  - make mt6737t-grandpplteser-lineageos_defconfig
  - make -j32
  - KERNEL_DIR=$PWD
  - ZIMAGE=$KERNEL_DIR/arch/arm/boot/*Image*

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken"
  #file_glob: true
  file: "$KERNEL_DIR/arch/arm/boot/*Image*"
  file: "$KERNEL_DIR/arch/arm/boot/compressed/*vmlinux*"
  on:
    tags: false
    repo: ALGPHELLO/android_kernel_samsung_grandpplte
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
